import re
p=re.compile('[a-c]')
m=p.match("a")
print(m)
p=re.compile('[a-c]')
m=p.match("b")
print(m)
p=re.compile('[a-c]')
m=p.match("c")
print(m)
p=re.compile('[1-3]')
m=p.match("1")
print(m)
p=re.compile('[1-3]')
m=p.match("1. CSV")
print(m)
p=re.compile('[1-3]')
m=p.match("3")
print(m)
